[project]
name = "ds-genai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docling>=2.61.1",
    "ipykernel>=7.1.0",
    "markitdown[all]>=0.1.3",
    "pandas>=2.3.3",
]
